# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1faUNtlnsQaU5_IYoZdJ8pUD6zZkW1msH
"""

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y == 0:
      return "Error! Cannot divide by zero"
    return x / y

def cal():
    while True:
        print("\nSelect Operation:")
        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Division")
        print("5. Exit")

        choice = input("Enter choice (1/2/3/4/5): ")

        if choice == '5':
            print("Exiting the calculator. Goodbye!")
            break

        if choice in ['1', '2', '3', '4']:
            try:
                n1 = float(input("Enter first number: "))
                n2 = float(input("Enter second number: "))
            except ValueError:
                print("Invalid input. Please enter numeric values.")
                continue

            if choice == '1':
                print("Result:", add(n1, n2))
            elif choice == '2':
                print("Result:", subtract(n1, n2))
            elif choice == '3':
                print("Result:", multiply(n1, n2))
            elif choice == '4':
                print("Result:", divide(n1, n2))
        else:
            print("Invalid choice")


cal()

